# Site Info
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site settings
title: James Burnside
description: >- # this means to ignore newlines until "baseurl:"
  Blog by Burnside
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jamesburnside.github.io"

# Dev Settings
show-newsletter: # true
show-suggestions: # true

# Author settings
author-name:  James Burnside
author-image: https://avatars.githubusercontent.com/u/2684369?v=4
author-job:   Software Developer at Microsoft
author-email: mail@jamesburnside.com
about-author: Blog on things I've worked on, things I found interesting, or rants I wanted to get off my chest.

# Social Settings
social-github: jamesburnside
social-linkedin: jameseburnside
social-twitter:
social-facebook:
social-pinterest:
social-instagram:
social-youtube:
social-vk:   

# Contact Me (formspree)
formspree-endpoint: f/xjvjabwq

# Newsletter
# mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
# google-analytics: # Add your identifier. For example UA-99631805-1

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - docs/
